### ISSUE TITLE
[legendPosition]="below" is not working in charts which provide this property

### ISSUE THREAD

**Issue by Oliverq755** [swimlane/ngx-charts#1080]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**

After providing the [legendPosition]="below", it get this properties in my template however it doesn't reflect on my UI.  The legends still stay in the default position. 

**Expected behavior**

As per the value provided to the [legendPosition] property, it should place the legends to the repective position with repect the graph. 

**Reproduction of the problem**

- create a template with simple angular app
- add any chart which has [legendPosition] property supported
- add [legendPosition]="below"
- run your application

**What is the motivation / use case for changing the behavior?**

- stock market graphs
- business KPI graphs
- Business Analytics Graphs

**Please tell us about your environment:**

* **ngx-charts version:** 8.0.2

* **Angular version:** 7.2.1

* **Browser:** [ Chrome XX  ]

* **Language:** [all | TypeScript 2.7  | ES6/7 | ES5]

**Screenshots of code with the proper output is attached below:** 

![original](https://user-images.githubusercontent.com/34798266/51375529-22ed5180-1b2c-11e9-8bef-90b20b9b06be.png)
![screenshot from 2019-01-18 14-18-16](https://user-images.githubusercontent.com/34798266/51375538-28e33280-1b2c-11e9-95bc-6def5cc26117.png)

**Comment by marjan-georgiev** [comment]
You need to pass it as a string, not a variable.

You are doing `[legendPosition]="below"`.
You need to either do ` [legendPosition]="'below'"`, or ` legendPosition="below"`

**Comment by Oliverq755** [comment]
Tried both suggestion (i.e [legendPosition]="'below'", or legendPosition="below") but still the issue exists (showing on the right side).

**Comment by marjan-georgiev** [comment]
Could you reproduce it in a stackblitz please?

**Comment by jcuypers** [comment]
I can confirm that `[legendPosition]="'below'"` for AOT/Prod work (otherwise it doesn't want to compile).  However the side-effect is that when using `[legendPosition]="'below'"` in dev, you get a legend which is positioned under the chart, but all items are on 1 horizantal line, which isn't responsive.   If I use `[legendPosition]="below"` in dev, I get a legend positioned under the chart, which items vertical (1 on each line, which is responsive).

**Comment by jcuypers** [comment]
I just want to share what I have got now (and gives me what I needed personally):   

```
    [legend]="true"
    [legendTitle]=null
    [legendPosition]=null
```

This gives me a legend, without title,  under the chart (with items vertically positioned, and legend width adapts to size of the container.  I have some resizing logic to make the chart "behave" / responsive

**Comment by sarthaks95** [comment]
I tried with `[legendPosition]="bottom"`and it's working.

**Comment by manolait** [comment]
Can't bind to 'legendPosition' since it isn't a known property of 'ngx-charts-line-chart'.

**Comment by mukund-m** [comment]
In your component file , declare a variable as 
`below = LegendPosition.below`
then in your template code,  `[legendPosition]="below"`

**Comment by rafagsiqueira** [comment]
Small correction: LegendPosition.Below it appears. In the example [grouped horizontal bar chart](https://stackblitz.com/edit/swimlane-grouped-horizontal-bar-chart), I have noticed that schemeType also does not accept a string. It seems to accept enum ScaleType now as well.

**Comment by nsmithdev** [comment]
This feels like a unintended public api change.
`legendPosition="below"` and `[legendPosition]="'below'"` used to work.

The typing's for LegendPosition and several other properties were converted to enum in this commit.
https://github.com/swimlane/ngx-charts/commit/6d591944a7eaa2942b4b4c39c9d3526d28ceb1b9#diff-2b44a01a1e7fa13f98c84eeab10ca35a545d6da4479f57d4b86c9b26cbe08a3a

I would suggest the instead of:
```ts
export enum LegendPosition {
  Right = 'right',
  Below = 'below'
}
```

Something like this would still provide the benefits of type safety and still support the simple string values in templates.
```ts
export type LegendPosition : 'right' | 'below'
```

Here is an Article that makes reference to the problem with enum and Angular templates only allowing the int not the string
https://www.grapecity.com/blogs/using-typescript-enums-angular-templates
_An issue arises when using enum type properties in Angular templates, however. 
Templates can only accept numeric constants, not named constants._ 

There is likely also a small performance impact vs the type of ('right' | 'below') which is only adding type checking
Here is what the enum compiles into.

```ts
export var LegendPosition;
(function (LegendPosition) {
    LegendPosition["Right"] = "right";
    LegendPosition["Below"] = "below";
})(LegendPosition || (LegendPosition = {}));
```

**Comment by malabuyocfritz1984** [comment]
`this aint working [legendPosition]="'below'" `

Type '"below"' is not assignable to type 'LegendPosition'.

Jaysus please update your documentation. this library is a major pain for us!!

**Comment by estibenlicona** [comment]
> below

This is the correct answer

**Comment by Biokimist** [comment]
[legendPosition]="LegendPosition.Below"

Work to move the legend below
But it is still unusable as the legend float under the next dom element and legend element are inlined without scrollbar.

**Comment by MohamedHassenBenadel** [comment]
maybe this is later , but this solution works for me : 

![1](https://github.com/swimlane/ngx-charts/assets/166857220/cb11d247-1df9-4b6d-a8b2-ffc4bb6e51b5)
![2](https://github.com/swimlane/ngx-charts/assets/166857220/643d58cf-1b64-480e-8eec-da6c02483f84)
