### ISSUE TITLE
Doesn't compile project with ivy

### ISSUE THREAD

**Issue by vdumbrav** [swimlane/ngx-charts#1168]
**Describe the bug**
Cannot compile project

**To Reproduce**
1. https://github.com/vdumbrav/angular-ivy-ngx-charts
2. run `serve` or `build --prod `

**Screenshots**
https://i.ibb.co/z5VZn7M/Screenshot-2019-05-16-16-42-06.png
https://pastebin.com/PRVaP7n9

**version**
ngx-chart v11.1.0
node v10.15.3
angular v8.0.0-rc.4

**Comment by vdumbrav** [comment]
https://github.com/angular/angular/issues/30512

**Comment by schmitch** [comment]
@marjan-georgiev I would be more than happy if there would be a "fast release" to test that in a staging setup of our application. Would it be possibe to get a 11.1.1 that addresses that? Or is it to much work/early to test ivy in a staging env?

**Comment by marjan-georgiev** [comment]
@schmitch I can release 11.2.0 (that would be the next version if I release now, since master already includes some new features), but that won't guarantee that ngx-charts will be compatible with ivy since I haven't upgraded the project to angular 8 yet.

I was planning to upgrade to angular 8 and release 12.0.0 to support all of that.

If you would like to test locally, I suggest cloning the repo, running `npm run install`, then `npm run package` and copying/linking the release files into your `node_modules`.

That said, Ivy is still not ready for production, but we will make the library compatible with it ahead of that.

**Comment by marjan-georgiev** [comment]
Released this in 11.2.0, since it has other features that people still running angular 7 might want to use.

The angular 8 upgrade is coming in 12.0.0

**Comment by vdumbrav** [comment]
@marjan-georgiev 
Will you fix the errors that come from ivy render? or will you wait until ivy is ready for production?
