### ISSUE TITLE
Possibility to disable the on enter animation

### ISSUE THREAD

**Issue by dnbo** [swimlane/ngx-charts#1195]
When adding a bar chart the actual entry is animated with some kind of slide in effect even though animations are disabled, which can cause weird stuttering behavior. This should be optional.

See example video clip @ https://streamable.com/9fjo7

**Comment by marjan-georgiev** [comment]
This is not an animation. The chart is rendering itself in two phases:
1. It renders using arbitrary dimensions, so that the axis are rendered
2. The chart then measures the space that the axis take within the available space, and re-renders with the new updated dimensions. 

This is why you see that effect.

**Comment by dnbo** [comment]
Enabling animations again resolved my issue though, but I understand how it works now! Thanks!
