### ISSUE TITLE
Can't bind to 'colors' since it isn't a known property of 'g'.

### ISSUE THREAD

**Issue by Anythingforlife** [swimlane/ngx-charts#1217]
Getting flowing error in  version 12.0.1.

Template error: Can't bind to 'colors' since it isn't a known property of 'g'.
    at createUnknownPropertyError 

Trying to implement pie chart :

<ngx-charts-pie-chart [view]="view" [scheme]="colorScheme" [results]="single" [legend]="showLegend"
    [explodeSlices]="explodeSlices" [labels]="showLabels" [doughnut]="doughnut" [gradient]="gradient"
    (select)="onSelect($event)">
</ngx-charts-pie-chart>

**Comment by marjan-georgiev** [comment]
Could you create a stackblitz where we can reproduce this please?

**Comment by Anythingforlife** [comment]
its reproducing when we use ,
 "angularCompilerOptions": {
    "enableIvy": true
  }

in tsconfig.app.json. its resolved now ,Thanks for response.

**Comment by dustintheweb** [comment]
experiencing the same - there seems to be some type of incompatibility when enabling the Ivy rendering engine (with at least the pie chart)

**Comment by dustintheweb** [comment]
https://stackblitz.com/edit/angular-axnjiu

@marjan-georgiev For whatever reason, the issue is not present in the stackblitz demo above (I am not 100% sure they allow the Ivy rendering engine to be toggled on), but if you download that exact app and run it locally, you will see the issue & the error in the console.
