### ISSUE TITLE
wrong sourcemapping url in index.js and index.min.js

### ISSUE THREAD

**Issue by alanpurple** [swimlane/ngx-charts#128]
in index.js
//# sourceMappingURL=index.map

should be index.js.map

this cause a 404 error

and in index.min.js
//# sourceMappingURL=index.js.map

should be index.min.js.map

**Comment by alanpurple** [comment]
@amcdnl 
plus,

sourcemapping url in release/index.min.js is currently
//# sourceMappingUrl=release/index.js.map

and it should be
//# sourceMappingUrl=index.min.js

**Comment by metavurt** [comment]
@alanpurple - I tried your fix, still running into a 404. What's your dev deps?

I literally have this: import 'NgxChartsModule' from '@swimlane/ngx-charts';

And that breaks. Error:

15 01 2017 23:21:06.887:WARN [web-server]: 404: /base/node_modules/@swimlane/ngx-charts.js
Chrome 55.0.2883 (Mac OS X 10.10.5) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/@swimlane/ngx-charts.js
	Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/@swimlane/ngx-charts.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?734fb5e7707872322802a5abd469dd1e330d5a75:962:29) [<root>]
	    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?734fb5e7707872322802a5abd469dd1e330d5a75:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?734fb5e7707872322802a5abd469dd1e330d5a75:345:33) [<root>]
	Error loading http://localhost:9876/base/node_modules/@swimlane/ngx-charts.js as "@swimlane/ngx-charts" from http://localhost:9876/base/dist/dev/app/leaders/leaders.component.spec.js'
Chrome 55.0.2883 (Mac OS X 10.10.5) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/@swimlane/ngx-charts.js
	Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/@swimlane/ngx-charts.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?734fb5e7707872322802a5abd469dd1e330d5a75:962:29) [<root>]
	    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?734fb5e7707872322802a5abd469dd1e330d5a75:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?734fb5e7707872322802a5abd469dd1e330d5a75:345:33) [<root>]
	Error loading http://localhost:9876/base/node_modules/@swimlane/ngx-charts.js as "@swimlane/ngx-charts" from http://localhost:9876/base/dist/dev/app/leaders/leaders.component.spec.js'

Finished in 0.003 secs / 0 secs

**Comment by metavurt** [comment]
And to confirm @alanpurple's findings - there are the following:
index.map
index.js.map
index.min.js.map


Wondering if index.map is conflicting?
Wondering why there isn't a index.min.map to mirror index.map

**Comment by alanpurple** [comment]
@metavurt  your systemJS setting is wrong, it's not ngx-charts.js, but release/index.js ( or index.min.js)

**Comment by metavurt** [comment]
Ah, thanks for the feedback @alanpurple. However, I had already tried those. So if I use:
import 'NgxChartsModule' from '@swimlane/release/index.js';
Typescript immediately throws an error, and when I ignore that, then not only do I get, from Karma, this error:
Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/@swimlane/release/index.js/index.js

but also (repeated, of course) the typescript error:
src/client/app/teampage/teampage.module.ts(10,33): error TS2307: Cannot find module '@swimlane/release/index.js'.

So that seems worse to me?

If I use:
import 'NgxChartsModule' from '@swimlane/ngx-charts/release/index.js

I get no typescript error, but still a Karma error:
404: /base/node_modules/@swimlane/ngx-charts/release/index.js

I'm using [angular-seed](https://github.com/mgechev/angular-seed), for what it's worth. I've added typings, taken away typings, added package addition like so (per angular-seed docs):
     this.addPackageBundles({
     name:'@swimlane/ngx-charts',
     path:'node_modules/@swimlane/ngx-charts/release/index.js', <--- this is *unlike* any other packages
     packageMeta:{
       main: 'index.js', <-- there is no index.js in the @swimlane directory; only 'ngx-charts' directory
       defaultExtension: 'js'
     }
   });

using both @swimlane/ngx-charts... and  @swimlane/release as paths, and I've taken that package out of the list.

Why is it that ngx-charts lists these:
release/index.js - UMD Version
release/index.min.js - UMD Version Minified

as their UMDs, when every other package that has UMD, has a distinct file named index.umd.js, and those files are usually in a 'bundle' dir?

I'm sorry, but per the instructions on the site, it seems like I should not be discovering consistent errors that disable the app, by simple adding one call to import.

I'll stop posting here; don't want to pollute/hijack this thread; just trying everything I know to get this implemented, in the most basic of ways.

thanks

**Comment by marjan-georgiev** [comment]
try
`import 'NgxChartsModule' from '@swimlane/ngx-charts/release/index.js';`

**Comment by metavurt** [comment]
Hi @marjan-georgiev, you're doing great work, sir!

Sorry to be confusing above, but I am using braces, not single quotations in my actual code. Was merely trying to be clear what I was importing from where, in conversational text.

As per my previous post, I still get Karma error with that particular import. I'm currently investigating angular-seed's docs and looking into some configs for karma that might help. If I find a solution, where should I post it, since this (I believe) is completely separate from the url mapping issue @alanpurple stated to start this thread?

**Comment by marjan-georgiev** [comment]
Thanks. I also changed the path from `'@swimlane/release/index.js';` to `'@swimlane/ngx-charts/release/index.js';`

System.js is looking for the file in the wrong path. Please try that and let me know if it fixes it.

**Comment by ThomasKientz** [comment]
Hi, 

I'm facing the same issue with an [angular seed](https://github.com/mgechev/angular-seed).

With : 
`import { NgxChartsModule } from '@swimlane/ngx-charts'`;

and this in the "additionalPackages" in tools/config/project.config.ts :
```
{
        name:'@swimlane/ngx-charts',
        path:'@swimlane/ngx-charts/release/index.js',
        packageMeta:{
          main: 'index.js',
          defaultExtension: 'js'
        }
}
```

@metavurt Have you succeeded to import it ?

**Comment by metavurt** [comment]
Ah, so sorry @ThomasKientz, I gave up on this for a bit. I can try to take a look tonight, and I'm GMT-8, for time context.

**Comment by ThomasKientz** [comment]
Would be very nice !

Thanks :)

Le dimanche 19 février 2017, William ONeal III <notifications@github.com> a
écrit :
> Ah, so sorry @ThomasKientz, I gave up on this for a bit. I can try to
take a look tonight, and I'm GMT-8, for time context.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/zT5fYkNNz4K32FI8W-MeDwgNW0lQ1DMaUw-PK6pDqlmaCKqZY3ffi7DWeRRvU_DAdygZ3QZh-lWRs8ItTpYXAteykLqXlj9SRs4lM2k50x0iGl9-tj_-gXuXDtD_8GE7y4kYYeMBjeMI_iKU0OdxaV0ciZkt5w=s0-d-e1-ft#https://github.com/notifications/beacon/AJr_FaumEfwss8NjMsf1lHE7ZrVJU9I0ks5rd2o3gaJpZM4LIefR.gif>

**Comment by ThomasKientz** [comment]
> Thanks. I also changed the path from '@swimlane/release/index.js'; to '@swimlane/ngx-charts/release/index.js';
> 
> System.js is looking for the file in the wrong path. Please try that and let me know if it fixes it.

@marjan-georgiev I'm facing the same issue with [this angular seed](https://github.com/mgechev/angular-seed). 

with this in `app.module.ts`  

> import { NgxChartsModule } from '@swimlane/ngx-charts/release/index.js';

I get in console :

<img width="743" alt="capture d ecran 2017-02-22 a 14 20 01" src="https://cloud.githubusercontent.com/assets/10157845/23201009/1d2eaf8c-f90a-11e6-8649-4392f044f626.png">

Any idea ?

Thanks

**Comment by marjan-georgiev** [comment]
@ThomasKientz You need to install the d3 modules and map them properly. They do not come bundled with ngx-charts.

**Comment by masterkrieger** [comment]
I just started using ngx-charts and haven't been able to run a simple line-chart successfully.
I'm getting similar error to @metavurt.

I started with the [angular-quickstart](https://github.com/angular/quickstart) and have ngx-charts and dependancies installed.

In my app.module.ts, I have the following code:

import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }  from './app.component';
import { NgxChartsModule } from '@swimlane/ngx-charts'; 
@NgModule({
  imports:      [ BrowserModule, NgxChartsModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }

Which gives me the error in browser:
![ngx-charts import error](https://cloud.githubusercontent.com/assets/1848365/25923297/c3a4617c-35aa-11e7-9dc3-4d1eb4ea1c21.png)

`Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/@swimlane/ngx-charts
	wrapFn@http://localhost:3000/node_modules/zone.js/dist/zone.js:1032:44
	runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:181:57
	invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:476:45
	Error loading http://localhost:3000/@swimlane/ngx-charts as "@swimlane/ngx-charts" from http://localhost:3000/app/app.module.js — system.src.js:122:88`

**Comment by metavurt** [comment]
@masterkrieger  - sorry to hear that, man! So, it's been a bit too long that I've worked on my own project, so I do not completely remember how I got a line chart working BUT - please feel free to dl from here: [https://github.com/metavurt/bowleague](https://github.com/metavurt/bowleague) -- the chart is in the team page component. You can see it here, live: [http://weo3.com/bowleague/](http://weo3.com/bowleague/) -- under teams -> stats. On desktop view, not very good; mobile view just fine. I had literally got it working, and was working on the height parameter being correctly generated.

Wish I could remember how exactly I got it past the 404s and other persistent errors, but I hope you can at least check the files against yours and find a difference that helps you.

Someday this is hopefully resolved for good!

**Comment by ColaColin** [comment]
Any new insights on how to fix this?

Also getting it with the angular seed and standard installations instructions provided by ngx-charts.
