### ISSUE TITLE
Angular 9 error in IE11

### ISSUE THREAD

**Issue by ThRintelen** [swimlane/ngx-charts#1372]
**Describe the bug**
Angular 9 project start with js error message on IE11.
vendor.js - there is " for (let value of values) " and i think let dont work in for on ie11

**Screenshots**
<img width="523" alt="Bildschirmfoto 2020-02-13 um 13 55 03" src="https://user-images.githubusercontent.com/11328544/74437492-7da8c800-4e68-11ea-9db3-3ebcaba1658e.png">

**ngx-charts version**
13.0.2 with Angular 9.0.1

**Additional context**
i use es5 as target

**Comment by ChaseOxide** [comment]
I believe this issue is related to #1369, maybe you can try out the solutions mentioned in the comments

**Comment by Benno007** [comment]
Using `resolutions` is the only scenario that works in my case: Angular 9 with Ivy enabled, needing to support IE11 (using webpack instead of angular cli (and unable to swap to angular cli), so can't do differential loading). We could have either disabled Ivy and used a lower version of ngx-charts, or pinned d3, according to this (https://github.com/swimlane/ngx-charts/issues/1369#issuecomment-586410664).

Would it be possible to get this PR in? https://github.com/swimlane/ngx-charts/pull/1379 Or do you intend on dropping support for IE11 (and requiring we use babel)

**Comment by NaderAbbasi** [comment]
We have also encountered this error with d3-array. How should we resolve it?
We use the version 14.0.0 and angular version 9
any solution or work around?

**Comment by jliang6** [comment]
Here are the only combination that I found solved the problem:

- swimlane/ngx-charts@13.0.0 (Note that 13.0.1, 13.0.3, 13.0.4, 14.0.0, 16.0.0 are not working)

- Needs to install npx and use https://www.npmjs.com/package/npm-force-resolutions

- package.json with:
```
"resolutions": {
  "d3-array": "1.2.1",
  "d3-scale": "1.0.6"
}
```

- Preinstall:
```
"scripts": {
  "preinstall": "npx npm-force-resolutions"
}
```

After that, check to see if ngx-charts, d3-array and d3-scale versions are correct in node_modules.  Plus you need to check in the package-lock.json to have the right versions under ngx-charts.
