### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by pardan** [swimlane/ngx-charts#1764]
my advanced pie chart look like this :
https://i.postimg.cc/CKfg90R0/snachart.png

how to decrease font size ? or make it clear
thanks

**Comment by Spaceman2019** [comment]
Hi, I'm using the version 20.1.0 and I have the same problem. When will the bug be fix?

**Comment by mario-alva** [comment]
Hi @pardan, thanks for your question. 

In order to change the font size, you can currently modify/overwrite the styles manually. (either font-size, font-family, color..)

In this screenshot I pointed out the names of the classes you will have to modify according to the different labels present on the chart's legend.
![image](https://user-images.githubusercontent.com/74981795/192873190-ca5627d8-9cb1-4ea7-8f2c-0ebd62daac84.png)

Let me know if you have more questions. Thanks!
