### ISSUE TITLE
asynchronous data?

### ISSUE THREAD

**Issue by 72gm** [swimlane/ngx-charts#190]
Hi,

With a lack of documentation (I know it is early days) I am having significant issues binding to a data service in a way I'd like. I have a data collection I "bind" to the chart but because the collection needs to be initialised empty (or the chart blows up) then it won't show anything because it thinks there is nothing to show.

If I add an *ngIf based around only creating the graph when the collection is  > 0 then it will bind to the first item only. 

I could do this synchronously and wait for all the data to come back but I'd rather update it as and when the data comes back - because there may be a lot.

**So really my question is**: do you have an asynchronous example or any rebind/refresh/add/delete methods that I can play around with?

Thanks

**Comment by marjan-georgiev** [comment]
We have a streaming data example in our demo page. Turn on real time in the Data menu and you should see it. Make sure your data is immutable so that change detection triggers.

We have an open issue for handling undefined/bad data: https://github.com/swimlane/ngx-charts/issues/158

In the future, please use the gitter chat to ask questions and use github issues only for feature requests and bug reports. Thanks!

**Comment by 72gm** [comment]
what an where is gitter chat?|

**Comment by marjan-georgiev** [comment]
https://gitter.im/swimlane/ngx-charts
