### ISSUE TITLE
Number Card Chart series value is beeing rounded

### ISSUE THREAD

**Issue by yaronmil** [swimlane/ngx-charts#227]
i dont want round the number for examplae 99.995 
any ideas ?

**Comment by marjan-georgiev** [comment]
We should modify the number card to pass custom formatter, in a similar way we support passing axis tick formatters.

**Comment by yaronmil** [comment]
or dont format the number at all , display it 'as is'

**Comment by marjan-georgiev** [comment]
That could be a problem when you have a number with many decimals, so in most use cases you actually want to round it, which is why we do it by default. Adding custom formatters would allow people to not round if they don't want to, and also do a lot of other different things, like prepend or append text (currency symbols, units, etc.)

**Comment by yaronmil** [comment]
good point .
i was thinking that the value should be  displayed  as he was passed to the element.
but it is always nice to have a formatter to applay some logic to the value.

so for meanwhile is there any hack ?

**Comment by Hypercubed** [comment]
`valueFormatting` is added in #325
