### ISSUE TITLE
Page lag and slow with data above 1000 data points

### ISSUE THREAD

**Issue by jasonhue8183** [swimlane/ngx-charts#413]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
page become slow and lag with just only 1440 data point rendered in chart. 

**Expected behavior**
no lag

**Reproduction of the problem**
line chart with timeline enable with above 1000 data. 

**What is the motivation / use case for changing the behavior?**
cannot handle big data. 

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x
ngx-charts version : 5.1.2

* **Angular version:** 2.x.x
Angular  : 4.1.1

* **Browser:**
All

* **Language:** [all | TypeScript 2.3.2 |  ES5]

**Comment by tariknz** [comment]
Seems like there is quite a performance hit compared to d3 wrapper solutions. Especially with higher data points. Been testing a stacked area graph with 8 series and 100 values per series. It lags like crazy.

I saw another issue #249 discussing this and it was pointed out that a canvas approach would be better than SVG but I'm curious to see if there is any work being done to tackle this problem.

**Comment by tariknz** [comment]
Here is a plunk of an example: 
https://plnkr.co/edit/1EG5MqQxUMKSATrrJoF8?p=preview

**Comment by PolarbearDK** [comment]
We are also experiencing this with stacked horizontal bar chart and area chart.

**Comment by mrv777** [comment]
I'm also experiencing lag with line charts, especially if I enable timeline and try to use it.  It slows to a crawl and the timeline is not usable as there is a delay of many seconds.  I think I currently have less then 100 points too.

**Comment by jimmykane** [comment]
Going away from this easy to use lib because of this. What is the purpose of this if above 1000 points the browser gets stuck ?

**Comment by tobigit** [comment]
We have also big performance problems with big data. Our line and area charts handling 10 series with each 150 data point. Drawing the charts and the mouse-hover-effect with creating tooltips and mark data-points is so incredible slow.

**Comment by jimmykane** [comment]
This is due to : https://github.com/swimlane/ngx-charts/issues/439 
This whole lib needs refactor.

**Comment by isalgueiro** [comment]
This is unusable with more than a few dozens of data points:
- ~21s to render an area chart with 2017 data points. 
- One full second with 289 data points. 
- 164ms with 13 data points.

**Comment by marjan-georgiev** [comment]
We refactored the tooltips of line and area charts and improved performance in version 6.0.0. Here's a plunkr with 1000 data points:
https://plnkr.co/edit/hTPaexbMyYbX8xJC38Ja?p=preview

**Comment by marjan-georgiev** [comment]
> This is due to : #439
As I explained in that issue, it was not because of that. The problem was the sheer number of components that were created (one circle component for each data point and one tooltip-area component for each value on the x axis). This has been addressed. 

> This whole lib needs refactor.
I would be happy to review any pull requests you submit in that direction.

**Comment by jimmykane** [comment]
@marjan-georgiev I admit I exaggerated with 'whole lib'. However, the issue was indeed related. This is because the multiple components would trigger changes too often. 

As commented on the PR, I will offer on your charts as well as an option cause they are quite well done. 

I have tested the change from the PR and it does solve the problem with some data chopping. 
FYI due to the optimizations experimented with trying to get this to work, I learned that it is suggested that the number of data points you load at first change/init should not exceed the 10nth of the width of the component. Then you should progressively load them etc.

**Comment by tariknz** [comment]
@marjan-georgiev thank you this is awesome!! Performing much better now. Appreciate your work!

Also reran the plunk I posted earlier and its smooth as butter.

**Comment by CsibiNorbert** [comment]
Any ideas that can possibly slow down the tooltip for ngx-charts? I`m talking more specifically about the ngx-charts-pie-chart
