### ISSUE TITLE
Custom formatting for values

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ngx-charts#51]
Allow specifying custom date formatting via input properties on the charts.

This would allow us to specify the representation of numbers and dates, as well as add prefixes and suffixes to their string representations in axis labels, legends, and tooltips.

**Comment by emoralesb05** [comment]
This would be awesome since sometimes we need to represent big numbers as `8M` or `79K` in the axis labels BUT have the full value show in tooltips.

**Comment by marjan-georgiev** [comment]
We added `xAxisTickFormatting` and `yAxisTickFormatting` inputs to all charts that have X and Y axis.

They accept a function, in which you can return a string that will be displayed in place of the axis tick label.

If you want to hide a label, just return an empty string.

Example:

```
axisFormat(val) {
  return '$' + val.toLocaleString(); 
}
```

**Comment by austindick** [comment]
Is there an example of this I can use for reference?

**Comment by salcio** [comment]
And how can we apply the same formatting to tooltip and line-chart line label

**Comment by BoJIbFbI4** [comment]
waiting for some example;
I need to use full time (DD-MM-YY, hh:mm:ss') formatting, but for xAxis I need (DD-MM) formatting.

**Comment by amrit-kumar** [comment]
I have a problem in using Custom formatting for values:
I am using function like this:
`(window:resize)="onResize($event)" 
  [scheme]="colorScheme"
  [results]="single"
  [gradient]="gradient"

  [xAxis]="showXAxis"
  [yAxis]="showYAxis"
  [legend]="showLegend"
  [showXAxisLabel]="showXAxisLabel"
  [showYAxisLabel]="showYAxisLabel"
  [xAxisLabel]="xAxisLabel"
  [yAxisLabel]="yAxisLabel"
  [xAxisTickFormatting]="xAxisTickFormatting"
  [yAxisTickFormatting]="yAxisTickFormatting"
  (select)="onSelect($event)"
  (legendLabelClick)="onLegendLabelClick($event)"
  (dblclick)="dblclick($event)"`

**and in my component i have written the function like this:**
` yAxisTickFormatting(value)  {
    let sessionContext = self.commonservice.getSessionContext()
   
 let globalExchangeRate =sessionContext.ExchangeRate;
   
 let globalCurrencySymbol=sessionContext.CurrencySymbol;
    value = this.commonservice.GetFormattedAmountForAllVisuals(value,globalExchangeRate,globalCurrencySymbol)
    return value
  }`

The problem is that here `this ` takes the current instance of chart but I need the instace of my component in order to use reusable functions of my service in angular 6.So I am Getting an error 
**...ERROR TypeError: Cannot read property 'getSessionContext' of undefined**

**Comment by shral** [comment]
Hi @marjan-georgiev ,
thank you for the great work! I was trying to use the feature but my formating should depend on one variable state in my component. I see that `this` of my component is not available, rather this of ngx-chart, any Idea how can I access my `this` in the formating function?
Best Regard
Shefki

**Comment by amrit-kumar** [comment]
@shral  use the following 
`    [xAxisTickFormatting]="xAxisTickFormatting.bind(this)"
`

**Comment by shral** [comment]
@amrit-kumar thank you for the idea! It seams to slow down my Application a lot and disturbs the behavior of ngx-charts, if I use bind. What's working for me (but I don't like mouch this solution) is declaring some global variable (outside of the component class) and use that to save `this` of my component.

**Comment by amrit-kumar** [comment]
Do it as follows:
in your component:
 ```
 public yAxisTickFormattingFn = this.yAxisTickFormatting.bind(this);
  public xAxisTickFormattingFn = this.xAxisTickFormatting.bind(this);

 yAxisTickFormatting(value) {
}
  xAxisTickFormatting(value) {
}
```
and in your html:
```
  [xAxisTickFormatting]="xAxisTickFormattingFn"
  [yAxisTickFormatting]="yAxisTickFormattingFn"
```

**Comment by Niaro** [comment]
@shral I believe the approach below is prettier of all the examples given before
```typescript
class SomeComponent {
    xAxisTickFormatting = value => `X ${value.toLocaleString()}`;
    yAxisTickFormatting = value => `Y ${value.toLocaleString()}`;
}
```

**Comment by shral** [comment]
@Niaro that's a very good Idea, thank you!

**Comment by Niaro** [comment]
@shral You are welcome!

**Comment by amrit-kumar** [comment]
can I have custom DataLabel  template as i want to show percentage value of all data for each chart in DataLabel  .

**Comment by ahmadnazih** [comment]
Is there a way to customize the data labels (eg: make it percentage instead of just numbers) ?

**Comment by nazirahmed-algo** [comment]
can I send the formatted HTML to show xAxis labels in the function return?
