### ISSUE TITLE
Combo Line and Bar chart not aligning 

### ISSUE THREAD

**Issue by svsgdev** [swimlane/ngx-charts#728]
The combo bar and line chart works fine if the no. of variables to display are around 10 but if there are around 50 variables the line chart does not align properly with the bar chart.

I am using IE 11 and I know you guys don't support IE11 and combo charts. Looking for inputs because it works fine when the variables are less.

**Comment by sbyzer** [comment]
Maybe it's a bit late, but I encountered the same issue and found out, that it's caused by this line

https://github.com/swimlane/ngx-charts/blob/4d9f58b1b8ec3127b408964c373613ee961dee71/demo/combo-chart/combo-chart.component.ts#L422

The bar chart rounds the range and the line chart doesn't, which leads to the alignment error. Changing this line to `.range([0, this.dims.width])` solved it for me.

**Comment by svsgdev** [comment]
I have made that change and now it aligns better if not perfect.Thank you.
